#!/bin/bash
if [ "$#" -ne 2 ]; then
    echo "Usage: ./debug_gdb {program} {test_number}"
    exit 1
fi

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH

if [ "$#" -eq  2 ]; then
    cuda-gdb --args ./$1 -e test/$2/output.raw -i test/$2/input0.raw,test/$2/input1.raw -o test/$2/attempt.raw -t matrix
fi
